# Generated by Django 4.1.7 on 2023-02-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursemembers_unique_together'),
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_task', to='courses.courses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachtotask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attach_task', to='task.task'),
        ),
    ]
