# Generated by Django 4.1.7 on 2023-02-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_homeworks_points_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.homeworks', verbose_name='homework_comment'),
        ),
    ]
