# Generated by Django 4.1.7 on 2023-02-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_comment_to_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_comment', to='task.homeworks'),
        ),
    ]
