# Generated by Django 4.1.7 on 2023-02-18 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='CourseMembers',
        ),
    ]
